### ISSUE TITLE
Adding in new tails results in not rendering character.

### ISSUE THREAD

**Issue by Derguns** [ponydevs/pixel.horse#107]
So I've got the fix in for the manes, which is great! But now if I go to add in new tails, I get a different bug. The tails have processed again with all of their patterns and show up in the selection list, however upon selecting a new tail the editor is unable to render the character, resulting in a blank area with no character. I can 'save' any of these though, and upon refreshing it remembers my selection- however, still no character image. Upon trying to enter a server, I get to the "loading..." screen for the server before it kicks me, which is different than what the manes did- they would instead reset back to a valid index.  

I also have a different bug with adding in facial markings - the markings are put into the spritesheet but just don't show up to be selected. I can put that in a different bug tracker if you'd like.

**Comment by BytewaveMLP** [comment]
Hm... As far as the PT Team and I can tell, this Shouldn't Happen™. Tail selections shouldn't even be at the soft limit yet. As per the usual routine, are you getting any errors, either on the server or the client, that would be useful ind debugging this?

**Comment by Derguns** [comment]
No error when compiling spritesheets or the build however I do get a console error! It says “cannot read property ox of undefined at: oY / e.draw / e.tryDraw / onFrame”. It looks like it’s looking for a property that isn’t assigned to this specific tail. I’m not sure if it’s a generation issue or a sprite sheet one .

**Comment by BytewaveMLP** [comment]
Speaking more with Chira, it sounds like this is another PT bug. Can you compile a development build, try running it, and give me the file name and line number it occurs on?

**Comment by BytewaveMLP** [comment]
Ah ha, looks like I found the issue.

New tails need an entry in the `wakeIndices` array in `src/ts/client/ponyDraw.ts`. There are 3 wake styles (used for swimming animations, I think), and you'll have to select one for each tail you make. I'm not sure what the difference is between 0, 1, and 2, but that's for you to experiment with.

**Comment by BytewaveMLP** [comment]
Also figured out the face marking issue:

In `src/ts/tools/create-sprites.ts`, there are two arrays, `head0Indices` and `head1Indices`. These map head patterns in the PSD to actual selectable head patterns. You'll notice there are less entries in these arrays; that's because some of the patterns in the PSD are simply mirrored versions of another. This is done so vertically asymmetric patterns will be flipped correctly when the player turns their head.

For every pattern you make, you'll need to add their indices to these arrays. If it's vertically symmetric, there's no need to worry about making a second pattern—just add the new pattern number to both arrays. If it isn't, you'll need to create a version with the index colors flipped. Place the un-flipped version's number in `head0Indices`, and the flipped version in `head1Indices`.

Hopefully that made sense.

**Comment by Derguns** [comment]
The tail fix worked great and the face markings do show up! However it looks like facial markings  also have the same reset-index softcap that manes did. Selecting one just resets back to a lower value.

**Comment by BytewaveMLP** [comment]
Facial markings is a new bug, it sounds like; tracked in #116
