### ISSUE TITLE
(Question) Can this be run on a Raspberry Pi?

### ISSUE THREAD

**Issue by KlonoaOfTheWind** [ponydevs/pixel.horse#136]
I'm interested in messing around with this a bit, but I think it'd be neat if a small computer such as a Raspberry Pi could host a small scale server. I probably won't have a ton of players or anything, most likely just me, so I don't think that will be an issue. Again, just looking to screw around with it. Might open it to a few friends in a discord server, if I figure things out.

Would this run on the ARM architecture, and would the process be similar to getting it running on a normal Windows machine?

**Comment by BytewaveMLP** [comment]
Actually, yes. @Tschrock set up a working server on a Pi 4. However, due to the resource requirements of the build process, you'll have to run a build on an external machine and copy it over to the Pi somehow (that is, unless your Pi somehow has >6GB of memory).

The process should be identical—Node.js is cross-platform. You'll need to source a build of Node 9 (or 10, if you must) for ARM from somewhere, but that's not impossible. Mongo (and nginx optionally) should have ARM builds as well.

**Comment by Tschrock** [comment]
Indeed it can, I've done so myself on the newer 4GB Raspberry Pi 4

It's almost the same as a regular install, just with a few tweaks:

1. Raspbian doesn't have updated packages for things like MongoDB, so I used an unofficial Ubuntu image from https://jamesachambers.com/raspberry-pi-4-ubuntu-server-desktop-18-04-3-image-unofficial/ to get things set up

2. The Pi will not have enough memory to build the game on the device - you will need to build the game on a more powerful computer, and then move the results onto the Pi (excluding the node_modules folder, and then reinstalling the needed dependencies with `npm i`)

3. There are some extra packages that you will need to install so that the 3 or 4 dependencies with native addons can compile properly: `sudo apt install build-essential pkg-config libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`. I also remember that there's one dependency that will fail to build anyway (node-canvas or something like that), but isn't needed to run the game so you can ignore that error.

**Comment by KlonoaOfTheWind** [comment]
Ah, interesting. I assume then its strongly recommended to use a Pi 4, the one with 4GB of RAM then? I've only got the Pi 2 B, which only has 1GB of RAM and the processor is slower (even under an overclock).

And it almost sounds like I'd be better off using my old laptop for this too, as that happens to have 8 GB of RAM. I'd just need to get a hard drive for it.

**Comment by BytewaveMLP** [comment]
A Pi 2 is probably underpowered for this, yes. Node and Mongo are pretty heavyweight, so the application is gonna choke out on resources pretty quickly. The higher-spec the machine, the better.

**Comment by KlonoaOfTheWind** [comment]
Noted.

I wouldn't have any trouble running it directly on this machine but I just had to ask. It's always nice to have a dedicated machine for running servers and such. Anyways, appreciate the responses.
